name: Convert Markdown to HTML

on:
  push:
    branches: [ main ]
    paths:
      - 'index.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install markdown CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Convert index.md to index.html
        run: |
          pandoc index.md -f markdown -t html -s -o index.html

      - name: Commit generated index.html
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-generate index.html from index.md"
          git push
